name: Frontend CI

on:
  push:
    branches:
      - master
      - dev-frontend
  pull_request:
    branches:
      - master
      - dev-frontend

jobs:
  test:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend-app

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: 'frontend-app/yarn.lock'
      - run: yarn install --frozen-lockfile
      - run: yarn run prod:test
